# Generated by Django 3.2.5 on 2021-08-01 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
