# Generated by Django 3.2.5 on 2021-08-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210802_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='when',
        ),
    ]
